-- Identity tables (docs/er_model.md part 1, decision D-019).
-- The auth_* tables and users are the shape Better Auth expects, with snake_case names; a test
-- (src/modules/identity/schema.test.ts) fails if Better Auth wants a column that is missing here.
-- Primary keys are UUIDs generated by the application (version 7).

CREATE TABLE users (
  id                     uuid PRIMARY KEY,
  name                   text        NOT NULL,
  -- Patients may have no email. Better Auth needs one, so a placeholder ending in
  -- @no-email.invalid is stored and treated as "no email" by the application (D-020).
  email                  text        NOT NULL UNIQUE,
  email_verified         boolean     NOT NULL DEFAULT false,
  image                  text,
  phone_number           text        UNIQUE,
  phone_number_verified  boolean     NOT NULL DEFAULT false,
  -- Phone recycling defence (D-019): when the phone was last proven, when the account was last
  -- used, and when the number was last changed.
  phone_verified_at      timestamptz,
  last_active_at         timestamptz,
  phone_changed_at       timestamptz,
  two_factor_enabled     boolean     NOT NULL DEFAULT false,
  status                 text        NOT NULL DEFAULT 'active',
  created_at             timestamptz NOT NULL DEFAULT now(),
  updated_at             timestamptz NOT NULL DEFAULT now(),
  deleted_at             timestamptz,
  CONSTRAINT users_status_check CHECK (status IN ('active', 'locked', 'deleted')),
  CONSTRAINT users_phone_e164_check CHECK (phone_number IS NULL OR phone_number ~ '^\+[1-9][0-9]{7,14}$')
);
CREATE TRIGGER users_set_updated_at BEFORE UPDATE ON users
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE auth_sessions (
  id          uuid PRIMARY KEY,
  user_id     uuid        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  token       text        NOT NULL UNIQUE,
  expires_at  timestamptz NOT NULL,
  ip_address  text,
  user_agent  text,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX auth_sessions_user_idx    ON auth_sessions (user_id);
CREATE INDEX auth_sessions_expires_idx ON auth_sessions (expires_at);
CREATE TRIGGER auth_sessions_set_updated_at BEFORE UPDATE ON auth_sessions
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE auth_accounts (
  id                        uuid PRIMARY KEY,
  user_id                   uuid        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  account_id                text        NOT NULL,
  provider_id               text        NOT NULL,
  access_token              text,
  refresh_token             text,
  id_token                  text,
  access_token_expires_at   timestamptz,
  refresh_token_expires_at  timestamptz,
  scope                     text,
  password                  text,
  created_at                timestamptz NOT NULL DEFAULT now(),
  updated_at                timestamptz NOT NULL DEFAULT now(),
  -- One external account (for example one Google sub) belongs to exactly one user.
  CONSTRAINT auth_accounts_provider_unique UNIQUE (provider_id, account_id)
);
CREATE INDEX auth_accounts_user_idx ON auth_accounts (user_id);
CREATE TRIGGER auth_accounts_set_updated_at BEFORE UPDATE ON auth_accounts
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE auth_verifications (
  id          uuid PRIMARY KEY,
  identifier  text        NOT NULL,
  value       text        NOT NULL,
  expires_at  timestamptz NOT NULL,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX auth_verifications_identifier_idx ON auth_verifications (identifier);
CREATE INDEX auth_verifications_expires_idx    ON auth_verifications (expires_at);
CREATE TRIGGER auth_verifications_set_updated_at BEFORE UPDATE ON auth_verifications
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE auth_two_factor (
  id                         uuid PRIMARY KEY,
  user_id                    uuid        NOT NULL UNIQUE REFERENCES users (id) ON DELETE CASCADE,
  secret                     text        NOT NULL,
  backup_codes               text        NOT NULL,
  verified                   boolean     NOT NULL DEFAULT false,
  failed_verification_count  integer     NOT NULL DEFAULT 0,
  locked_until               timestamptz,
  created_at                 timestamptz NOT NULL DEFAULT now(),
  updated_at                 timestamptz NOT NULL DEFAULT now()
);
CREATE TRIGGER auth_two_factor_set_updated_at BEFORE UPDATE ON auth_two_factor
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE roles (
  id    smallint PRIMARY KEY,
  code  text     NOT NULL UNIQUE
);
INSERT INTO roles (id, code) VALUES
  (1, 'patient'), (2, 'doctor'), (3, 'admin'), (4, 'super_admin'), (5, 'support');
-- The set of roles is part of the code. The application cannot add or change one.
REVOKE INSERT, UPDATE, DELETE ON roles FROM app;

CREATE TABLE user_roles (
  user_id     uuid        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  role_id     smallint    NOT NULL REFERENCES roles (id),
  granted_by  uuid        REFERENCES users (id),
  granted_at  timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, role_id)
);
CREATE INDEX user_roles_role_idx ON user_roles (role_id);

-- Single-use account recovery codes. Only a hash is stored (D-019).
CREATE TABLE recovery_codes (
  id          uuid PRIMARY KEY,
  user_id     uuid        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  code_hash   text        NOT NULL,
  used_at     timestamptz,
  created_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX recovery_codes_user_idx ON recovery_codes (user_id) WHERE used_at IS NULL;

-- Devices the patient unlocked with a second method. Only a hash of the device token is stored.
CREATE TABLE trusted_devices (
  id            uuid PRIMARY KEY,
  user_id       uuid        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  device_hash   text        NOT NULL UNIQUE,
  unlocked_at   timestamptz NOT NULL DEFAULT now(),
  expires_at    timestamptz NOT NULL,
  last_seen_at  timestamptz NOT NULL DEFAULT now(),
  revoked_at    timestamptz
);
CREATE INDEX trusted_devices_user_idx ON trusted_devices (user_id);
