import type { AuthMode, HttpMethod, RateLimitTier, Role } from "./types";

// The access-control matrix (P2-08): who may call each route, written by hand and kept apart
// from the route files on purpose. The matrix test (access-matrix.test.ts) loads every route
// and fails when
//   - a route exists that is not listed here (add it, and decide who may call it),
//   - a route listed here no longer exists,
//   - a route's settings differ from what is written here, or
//   - the running route lets a role in or keeps one out contrary to this table.
// Adding a route therefore always includes a deliberate line in this file.

export type MatrixEntry = {
  auth: AuthMode;
  /** Roles allowed after authentication. Empty means any role the `auth` mode admits. */
  roles: readonly Role[];
  /** What a signed-in caller with the wrong role sees. */
  roleDenied: "forbidden" | "not_found";
  rateLimit: RateLimitTier;
  audited: boolean;
  /** True when the route needs a sign-in within the last 15 minutes. */
  freshLogin: boolean;
  /**
   * True when a limited session (risky phone sign-in, second method not proven) is refused with
   * step_up_required. Every route that reads or changes the patient's stored data sets it.
   */
  fullSession: boolean;
  /**
   * For routes behind a login: true when a request with an empty body reaches the validator
   * (422), which proves the caller got past the gate without running the handler. Routes
   * without a body schema set false and are only checked for the denied cases.
   */
  probeAllowed: boolean;
  why: string;
};

export type RouteKey = `${HttpMethod} ${string}`;

export const ACCESS_MATRIX: Record<RouteKey, MatrixEntry> = {
  "GET /api/health": {
    auth: "public",
    roles: [],
    roleDenied: "forbidden",
    rateLimit: "public_read",
    audited: false,
    freshLogin: false,
    fullSession: false,
    probeAllowed: false,
    why: "Liveness probe for the load balancer. Writes nothing, shows nothing private.",
  },
  "GET /api/ready": {
    auth: "public",
    roles: [],
    roleDenied: "forbidden",
    rateLimit: "public_read",
    audited: false,
    freshLogin: false,
    fullSession: false,
    probeAllowed: false,
    why: "Readiness probe: database and cache ping, no details to the caller.",
  },
  "GET /api/auth/*": {
    auth: "public",
    roles: [],
    roleDenied: "forbidden",
    rateLimit: "public_read",
    audited: false,
    freshLogin: false,
    fullSession: false,
    probeAllowed: false,
    why: "Better Auth read endpoints (session lookup and similar). Each one checks its own cookie.",
  },
  "POST /api/auth/*": {
    auth: "public",
    roles: [],
    roleDenied: "forbidden",
    rateLimit: "write",
    audited: false,
    freshLogin: false,
    fullSession: false,
    probeAllowed: false,
    why: "Sign-in and sign-out. OTP send and verify also pass the OTP guard (limits, captcha, budget).",
  },
  "POST /api/v1/admin/invitations": {
    auth: "staff",
    roles: ["admin", "super_admin"],
    roleDenied: "not_found",
    rateLimit: "admin",
    audited: true,
    freshLogin: true,
    fullSession: false,
    probeAllowed: true,
    why: "Admin invites a staff member. Hidden (404) from every other role.",
  },
  "POST /api/v1/invitations/:token/enrol": {
    auth: "public",
    roles: [],
    roleDenied: "forbidden",
    rateLimit: "otp_verify",
    audited: false,
    freshLogin: false,
    fullSession: false,
    probeAllowed: false,
    why: "The invitation link is the credential. Fails closed if the cache is down.",
  },
  "POST /api/v1/invitations/:token/accept": {
    auth: "public",
    roles: [],
    roleDenied: "forbidden",
    rateLimit: "otp_verify",
    audited: true,
    freshLogin: false,
    fullSession: false,
    probeAllowed: false,
    why: "The invitation link is the credential, plus a first authenticator code.",
  },
  "GET /api/v1/specialties": {
    auth: "public",
    roles: [],
    roleDenied: "forbidden",
    rateLimit: "public_read",
    audited: false,
    freshLogin: false,
    fullSession: false,
    probeAllowed: false,
    why: "Public list. Counts only listed doctors.",
  },
  "GET /api/v1/doctors": {
    auth: "public",
    roles: [],
    roleDenied: "forbidden",
    rateLimit: "public_read",
    audited: false,
    freshLogin: false,
    fullSession: false,
    probeAllowed: false,
    why: "Public search. Only approved and active doctors; filters and sorts come from an allow-list.",
  },
  "GET /api/v1/doctors/:id": {
    auth: "public",
    roles: [],
    roleDenied: "forbidden",
    rateLimit: "public_read",
    audited: false,
    freshLogin: false,
    fullSession: false,
    probeAllowed: false,
    why: "Public profile of a listed doctor. Anyone not listed is 404. No contact details.",
  },
  "GET /api/v1/doctors/:id/slots": {
    auth: "public",
    roles: [],
    roleDenied: "forbidden",
    rateLimit: "public_read",
    audited: false,
    freshLogin: false,
    fullSession: false,
    probeAllowed: false,
    why: "Public free slots of a listed doctor. Anyone not listed is 404. Cached for seconds only.",
  },
  "POST /api/v1/appointments": {
    auth: "session",
    roles: ["patient"],
    roleDenied: "not_found",
    rateLimit: "write",
    audited: true,
    freshLogin: false,
    fullSession: true,
    probeAllowed: true,
    why: "A patient holds a slot for a profile they own (404 for anyone else's). Idempotent; capped open holds.",
  },
  "GET /api/v1/appointments": {
    auth: "session",
    roles: ["patient"],
    roleDenied: "not_found",
    rateLimit: "auth_read",
    audited: false,
    freshLogin: false,
    fullSession: true,
    probeAllowed: false,
    why: "A patient lists the bookings on their own account.",
  },
  "GET /api/v1/appointments/:id": {
    auth: "session",
    roles: ["patient", "doctor", "admin", "super_admin", "support"],
    roleDenied: "not_found",
    rateLimit: "auth_read",
    audited: false,
    freshLogin: false,
    fullSession: true,
    probeAllowed: false,
    why: "Owner account, assigned doctor, admin and support only (policy appointment.read). Others see 404.",
  },
  "POST /api/v1/appointments/:id/cancel": {
    auth: "session",
    roles: ["patient", "doctor", "admin", "super_admin"],
    roleDenied: "not_found",
    rateLimit: "write",
    audited: true,
    freshLogin: false,
    fullSession: true,
    probeAllowed: true,
    why: "Owner, assigned doctor or admin (policy appointment.cancel). Reason from a fixed list. Final status depends on who cancels.",
  },
  "POST /api/v1/appointments/:id/reschedule": {
    auth: "session",
    roles: ["patient"],
    roleDenied: "not_found",
    rateLimit: "write",
    audited: true,
    freshLogin: false,
    fullSession: true,
    probeAllowed: true,
    why: "Owner only. A confirmed appointment that has not started, up to the reschedule limit.",
  },
  "GET /api/v1/doctor/appointments": {
    auth: "staff",
    roles: ["doctor"],
    roleDenied: "not_found",
    rateLimit: "auth_read",
    audited: false,
    freshLogin: false,
    fullSession: false,
    probeAllowed: false,
    why: "A doctor lists their own confirmed upcoming appointments.",
  },
  "POST /api/v1/appointments/:id/review": {
    auth: "session",
    roles: ["patient"],
    roleDenied: "not_found",
    rateLimit: "write",
    audited: true,
    freshLogin: false,
    fullSession: true,
    probeAllowed: true,
    why: "Only the account that booked a completed appointment (404 for anyone else). One review per appointment.",
  },
  "GET /api/v1/doctors/:id/reviews": {
    auth: "public",
    roles: [],
    roleDenied: "forbidden",
    rateLimit: "public_read",
    audited: false,
    freshLogin: false,
    fullSession: false,
    probeAllowed: false,
    why: "Public published reviews of a listed doctor. Reviewers are not named.",
  },
  "GET /api/v1/favorites": {
    auth: "session",
    roles: ["patient"],
    roleDenied: "not_found",
    rateLimit: "auth_read",
    audited: false,
    freshLogin: false,
    fullSession: true,
    probeAllowed: false,
    why: "A patient lists saved doctors of a profile on their own account.",
  },
  "POST /api/v1/favorites": {
    auth: "session",
    roles: ["patient"],
    roleDenied: "not_found",
    rateLimit: "write",
    audited: true,
    freshLogin: false,
    fullSession: true,
    probeAllowed: true,
    why: "A patient saves a listed doctor for their own profile (cap 50).",
  },
  "DELETE /api/v1/favorites": {
    auth: "session",
    roles: ["patient"],
    roleDenied: "not_found",
    rateLimit: "write",
    audited: true,
    freshLogin: false,
    fullSession: true,
    probeAllowed: true,
    why: "A patient removes a saved doctor from their own profile.",
  },
  "GET /api/v1/admin/reviews": {
    auth: "staff",
    roles: ["admin", "super_admin"],
    roleDenied: "not_found",
    rateLimit: "admin",
    audited: false,
    freshLogin: false,
    fullSession: false,
    probeAllowed: false,
    why: "The moderation queue. Hidden (404) from every other role.",
  },
  "POST /api/v1/admin/reviews/:id/moderate": {
    auth: "staff",
    roles: ["admin", "super_admin"],
    roleDenied: "not_found",
    rateLimit: "admin",
    audited: true,
    freshLogin: false,
    fullSession: false,
    probeAllowed: true,
    why: "Publish or hide a review. Hidden (404) from every other role.",
  },
  "GET /api/v1/doctor/availability": {
    auth: "staff",
    roles: ["doctor"],
    roleDenied: "not_found",
    rateLimit: "auth_read",
    audited: false,
    freshLogin: false,
    fullSession: false,
    probeAllowed: false,
    why: "A doctor reads only their own hours and time off.",
  },
  "PUT /api/v1/doctor/availability": {
    auth: "staff",
    roles: ["doctor"],
    roleDenied: "not_found",
    rateLimit: "write",
    audited: true,
    freshLogin: false,
    fullSession: false,
    probeAllowed: true,
    why: "A doctor replaces their own weekly hours. Booked appointments are not moved.",
  },
  "POST /api/v1/doctor/time-off": {
    auth: "staff",
    roles: ["doctor"],
    roleDenied: "not_found",
    rateLimit: "write",
    audited: true,
    freshLogin: false,
    fullSession: false,
    probeAllowed: true,
    why: "A doctor blocks days for themselves (capped). Reports bookings it overlaps.",
  },
  "DELETE /api/v1/doctor/time-off/:id": {
    auth: "staff",
    roles: ["doctor"],
    roleDenied: "not_found",
    rateLimit: "write",
    audited: true,
    freshLogin: false,
    fullSession: false,
    probeAllowed: false,
    why: "A doctor removes their own time off only; another doctor's entry is 404.",
  },
  "POST /api/v1/payments/orders": {
    auth: "session",
    roles: ["patient"],
    roleDenied: "not_found",
    rateLimit: "payments",
    audited: true,
    freshLogin: false,
    fullSession: true,
    probeAllowed: true,
    why: "Only the account that holds the appointment (404 for anyone else). The amount is the held fee, never from the client. Idempotent; sensitive tier fails closed.",
  },
  "POST /api/v1/admin/payments/:id/refund": {
    auth: "staff",
    roles: ["admin", "super_admin"],
    roleDenied: "not_found",
    rateLimit: "admin",
    audited: true,
    freshLogin: true,
    fullSession: false,
    probeAllowed: true,
    why: "Admin refund of a received payment, in full or in part. Fresh sign-in, Idempotency-Key, capped by what is left; patients, doctors and support get 404. The ledger follows when the gateway confirms.",
  },
  "GET /api/v1/payments/:id/invoice": {
    auth: "session",
    roles: ["patient"],
    roleDenied: "not_found",
    rateLimit: "payments",
    audited: true,
    freshLogin: false,
    fullSession: true,
    probeAllowed: false,
    why: "Only the account that paid (404 for anyone else, including the doctor and admins). A short-lived download link, or 'preparing' until the worker has drawn the PDF.",
  },
  "POST /api/v1/admin/payouts": {
    auth: "staff",
    roles: ["admin", "super_admin"],
    roleDenied: "not_found",
    rateLimit: "admin",
    audited: true,
    freshLogin: true,
    fullSession: false,
    probeAllowed: true,
    why: "Claims each doctor's balance for a finished period. Admins only (404 for everyone else), fresh sign-in; the same period again creates nothing.",
  },
  "GET /api/v1/admin/payouts/export": {
    auth: "staff",
    roles: ["admin", "super_admin"],
    roleDenied: "not_found",
    rateLimit: "admin",
    audited: true,
    freshLogin: true,
    fullSession: false,
    probeAllowed: false,
    why: "The CSV to pay from: names, registration numbers and amounts, never bank or contact details. Admins only, fresh sign-in, always a download.",
  },
  "POST /api/v1/admin/payouts/:id/paid": {
    auth: "staff",
    roles: ["admin", "super_admin"],
    roleDenied: "not_found",
    rateLimit: "admin",
    audited: true,
    freshLogin: true,
    fullSession: false,
    probeAllowed: true,
    why: "Records that a payout was sent, once. Admins only, fresh sign-in.",
  },
  "GET /api/v1/referrals/me": {
    auth: "session",
    roles: ["patient"],
    roleDenied: "not_found",
    rateLimit: "referral",
    audited: false,
    freshLogin: false,
    fullSession: true,
    probeAllowed: false,
    why: "A patient's own code and counts; never names anyone invited. 404 while the `referrals` flag is off.",
  },
  "POST /api/v1/referrals/redeem": {
    auth: "session",
    roles: ["patient"],
    roleDenied: "not_found",
    rateLimit: "referral",
    audited: true,
    freshLogin: false,
    fullSession: true,
    probeAllowed: true,
    why: "A new patient enters a friend's code. Once per person, never your own, only before a first booking, capped per referrer; every refusal reads the same. Fails-closed rate limit against guessing; 404 while the flag is off.",
  },
  "GET /api/v1/appointments/:id/consents": {
    auth: "session",
    roles: ["patient"],
    roleDenied: "not_found",
    rateLimit: "auth_read",
    audited: false,
    freshLogin: false,
    fullSession: true,
    probeAllowed: false,
    why: "The texts still to be agreed to for this appointment's patient. Only the account that owns the profile (404 for anyone else).",
  },
  "POST /api/v1/appointments/:id/consents": {
    auth: "session",
    roles: ["patient"],
    roleDenied: "not_found",
    rateLimit: "write",
    audited: true,
    freshLogin: false,
    fullSession: true,
    probeAllowed: true,
    why: "Records agreement to the texts currently asked for (an old or unrelated text is refused). A parent agreeing for a child is recorded as such. Only the profile's account.",
  },
  "POST /api/v1/consents/:id/withdraw": {
    auth: "session",
    roles: ["patient"],
    roleDenied: "not_found",
    rateLimit: "write",
    audited: true,
    freshLogin: false,
    fullSession: true,
    probeAllowed: false,
    why: "Only the person who gave the agreement (404 for anyone else). Video visits close until they agree again.",
  },
  "POST /api/v1/consultations/:appointmentId/join": {
    auth: "session",
    roles: ["patient", "doctor"],
    roleDenied: "not_found",
    rateLimit: "write",
    audited: true,
    freshLogin: false,
    fullSession: true,
    probeAllowed: false,
    why: "Only the patient's account or the assigned doctor (404 for anyone else). Booked, paid, inside the join window and, for the patient, consent on record, in that order. Token for one room and one number only.",
  },
  "POST /api/v1/consultations/:appointmentId/token": {
    auth: "session",
    roles: ["patient", "doctor"],
    roleDenied: "not_found",
    rateLimit: "write",
    audited: true,
    freshLogin: false,
    fullSession: true,
    probeAllowed: false,
    why: "Renewal for someone already in the room. Refused after the consultation ended, after the seat was revoked, or well after the booked time.",
  },
  "POST /api/v1/consultations/:appointmentId/end": {
    auth: "session",
    roles: ["doctor"],
    roleDenied: "not_found",
    rateLimit: "write",
    audited: true,
    freshLogin: false,
    fullSession: true,
    probeAllowed: false,
    why: "Only the assigned doctor (404 for anyone else). Revokes every seat so no token can be renewed.",
  },
  "POST /api/v1/payments/verify": {
    auth: "session",
    roles: ["patient"],
    roleDenied: "not_found",
    rateLimit: "payments",
    audited: true,
    freshLogin: false,
    fullSession: true,
    probeAllowed: true,
    why: "Owner of the appointment only (404 otherwise). The checkout signature is checked, then the gateway is asked; the browser is never believed about money.",
  },
  "POST /api/webhooks/razorpay": {
    auth: "public",
    roles: [],
    roleDenied: "forbidden",
    rateLimit: "webhook",
    audited: false,
    freshLogin: false,
    fullSession: false,
    probeAllowed: false,
    why: "Gateway callback. The HMAC over the raw body is the credential; a bad signature is refused and stored nowhere. Events are kept once in payment_events.",
  },
  "GET /api/v1/doctor/application": {
    auth: "staff",
    roles: ["doctor"],
    roleDenied: "not_found",
    rateLimit: "auth_read",
    audited: false,
    freshLogin: false,
    fullSession: false,
    probeAllowed: false,
    why: "A doctor reads only their own application. Everyone else sees 404.",
  },
  "PUT /api/v1/doctor/application": {
    auth: "staff",
    roles: ["doctor"],
    roleDenied: "not_found",
    rateLimit: "write",
    audited: true,
    freshLogin: false,
    fullSession: false,
    probeAllowed: true,
    why: "A doctor saves their own application; an approved one cannot be changed.",
  },
  "POST /api/v1/doctor/kyc-documents": {
    auth: "staff",
    roles: ["doctor"],
    roleDenied: "not_found",
    rateLimit: "write",
    audited: true,
    freshLogin: false,
    fullSession: false,
    probeAllowed: true,
    why: "A doctor asks for an upload slot for their own KYC document (capped per doctor and per type).",
  },
  "POST /api/v1/doctor/kyc-documents/:id/complete": {
    auth: "staff",
    roles: ["doctor"],
    roleDenied: "not_found",
    rateLimit: "write",
    audited: true,
    freshLogin: false,
    fullSession: false,
    probeAllowed: false,
    why: "Owner only: another doctor's document is 404. Checks the file, then queues the virus scan.",
  },
  "GET /api/v1/admin/doctors": {
    auth: "staff",
    roles: ["admin", "super_admin"],
    roleDenied: "not_found",
    rateLimit: "admin",
    audited: false,
    freshLogin: false,
    fullSession: false,
    probeAllowed: false,
    why: "The application queue. Hidden (404) from every other role.",
  },
  "GET /api/v1/admin/doctors/:id": {
    auth: "staff",
    roles: ["admin", "super_admin"],
    roleDenied: "not_found",
    rateLimit: "admin",
    audited: false,
    freshLogin: false,
    fullSession: false,
    probeAllowed: false,
    why: "One application with its documents. Hidden from every other role.",
  },
  "POST /api/v1/admin/doctors/:id/decision": {
    auth: "staff",
    roles: ["admin", "super_admin"],
    roleDenied: "not_found",
    rateLimit: "admin",
    audited: true,
    freshLogin: true,
    fullSession: false,
    probeAllowed: true,
    why: "Approve, reject, suspend or reinstate. Fresh sign-in; never on your own application.",
  },
  "POST /api/v1/admin/kyc-documents/:id/review": {
    auth: "staff",
    roles: ["admin", "super_admin"],
    roleDenied: "not_found",
    rateLimit: "admin",
    audited: true,
    freshLogin: true,
    fullSession: false,
    probeAllowed: true,
    why: "Accept or refuse a scanned document. Fresh sign-in; never your own.",
  },
  "GET /api/v1/admin/kyc-documents/:id/download": {
    auth: "staff",
    roles: ["admin", "super_admin"],
    roleDenied: "not_found",
    rateLimit: "admin",
    audited: true,
    freshLogin: true,
    fullSession: false,
    probeAllowed: false,
    why: "Short-lived link to a clean document only. Fresh sign-in and logged.",
  },
  "GET /api/v1/patients": {
    auth: "session",
    roles: ["patient"],
    roleDenied: "not_found",
    rateLimit: "auth_read",
    audited: false,
    freshLogin: false,
    fullSession: true,
    probeAllowed: false,
    why: "A patient lists the profiles on their own account. Other roles see 404.",
  },
  "POST /api/v1/patients": {
    auth: "session",
    roles: ["patient"],
    roleDenied: "not_found",
    rateLimit: "write",
    audited: true,
    freshLogin: false,
    fullSession: true,
    probeAllowed: true,
    why: "A patient adds a profile to their own account (capped at 10).",
  },
  "GET /api/v1/patients/:id": {
    auth: "session",
    roles: ["patient"],
    roleDenied: "not_found",
    rateLimit: "auth_read",
    audited: false,
    freshLogin: false,
    fullSession: true,
    probeAllowed: true,
    why: "Owner only: another account's profile is 404, same as a missing one.",
  },
  "PATCH /api/v1/patients/:id": {
    auth: "session",
    roles: ["patient"],
    roleDenied: "not_found",
    rateLimit: "write",
    audited: true,
    freshLogin: false,
    fullSession: true,
    probeAllowed: true,
    why: "Owner only. The minor flag is computed on the server, never sent.",
  },
  "DELETE /api/v1/patients/:id": {
    auth: "session",
    roles: ["patient"],
    roleDenied: "not_found",
    rateLimit: "write",
    audited: true,
    freshLogin: false,
    fullSession: true,
    probeAllowed: true,
    why: "Owner only soft delete of a family member's profile.",
  },
  "GET /api/v1/sessions": {
    auth: "session",
    roles: [],
    roleDenied: "forbidden",
    rateLimit: "auth_read",
    audited: false,
    freshLogin: false,
    fullSession: false,
    probeAllowed: false,
    why: "Any signed-in person lists their own sessions (the user id is in the query).",
  },
  "DELETE /api/v1/sessions": {
    auth: "session",
    roles: [],
    roleDenied: "forbidden",
    rateLimit: "write",
    audited: true,
    freshLogin: false,
    fullSession: false,
    probeAllowed: false,
    why: "Sign out everywhere. Deliberately not fresh-login: it is the emergency exit.",
  },
  "DELETE /api/v1/sessions/:id": {
    auth: "session",
    roles: [],
    roleDenied: "forbidden",
    rateLimit: "write",
    audited: true,
    freshLogin: false,
    fullSession: false,
    probeAllowed: true,
    why: "Ends one of the caller's own sessions; someone else's is 404.",
  },
  "POST /api/v1/data-requests": {
    auth: "session",
    roles: ["patient"],
    roleDenied: "not_found",
    rateLimit: "write",
    audited: true,
    freshLogin: true,
    fullSession: true,
    probeAllowed: true,
    why: "A patient asks for export or deletion of their own data. Needs a recent sign-in.",
  },
  "GET /api/v1/data-requests": {
    auth: "session",
    roles: ["patient"],
    roleDenied: "not_found",
    rateLimit: "auth_read",
    audited: false,
    freshLogin: false,
    fullSession: true,
    probeAllowed: false,
    why: "A patient lists their own requests (the user id is in the query).",
  },
  "GET /api/v1/me": {
    auth: "session",
    roles: [],
    roleDenied: "forbidden",
    rateLimit: "auth_read",
    audited: false,
    freshLogin: false,
    fullSession: false,
    probeAllowed: false,
    why: "Describes only the caller (id and roles). Used by the sign-in screens.",
  },
  "GET /api/v1/me/sign-in-methods": {
    auth: "session",
    roles: ["patient"],
    roleDenied: "not_found",
    rateLimit: "auth_read",
    audited: false,
    freshLogin: false,
    fullSession: false,
    probeAllowed: false,
    why: "A patient sees which sign-in methods their own account has (booleans only).",
  },
  "POST /api/v1/me/step-up/recovery-code": {
    auth: "session",
    roles: ["patient"],
    roleDenied: "not_found",
    rateLimit: "otp_verify",
    audited: true,
    freshLogin: false,
    fullSession: false,
    probeAllowed: true,
    why: "The one thing a limited session may do besides signing out: spend a recovery code. Five wrong codes lock guessing.",
  },
  "POST /api/v1/me/recovery-codes": {
    auth: "session",
    roles: ["patient"],
    roleDenied: "not_found",
    rateLimit: "write",
    audited: true,
    freshLogin: true,
    fullSession: true,
    probeAllowed: false,
    why: "A full, fresh session makes new recovery codes; a recycled number must not be able to.",
  },
  "GET /api/v1/me/recovery-codes": {
    auth: "session",
    roles: ["patient"],
    roleDenied: "not_found",
    rateLimit: "auth_read",
    audited: false,
    freshLogin: false,
    fullSession: true,
    probeAllowed: false,
    why: "Only a count of unused codes, to a full session.",
  },
  "GET /api/v1/me/devices": {
    auth: "session",
    roles: ["patient"],
    roleDenied: "not_found",
    rateLimit: "auth_read",
    audited: false,
    freshLogin: false,
    fullSession: true,
    probeAllowed: false,
    why: "The patient's own remembered devices (the user id is in the query).",
  },
  "DELETE /api/v1/me/devices/:id": {
    auth: "session",
    roles: ["patient"],
    roleDenied: "not_found",
    rateLimit: "write",
    audited: true,
    freshLogin: false,
    fullSession: true,
    probeAllowed: true,
    why: "Forget one of the patient's own devices; someone else's is 404.",
  },
  "POST /api/v1/security/not-me": {
    auth: "public",
    roles: [],
    roleDenied: "forbidden",
    rateLimit: "otp_verify",
    audited: true,
    freshLogin: false,
    fullSession: false,
    probeAllowed: false,
    why: "The link in a new-device notice is the credential: ends all sessions and forces step-up.",
  },
};
